rename

diff --git a/contrib/make_tor b/contrib/make_tor
--- a/contrib/make_tor
+++ b/contrib/make_tor
@@ -47,8 +47,8 @@ if [ "$BUILD_TYPE" = "wine" ] ; then
     binary="tor.exe"
 fi
 host_strip "$here/$pkgname/dist/bin/$binary"
-mkdir -p "$here/../electroncash/tor/bin"
-cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../electroncash/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
+mkdir -p "$here/../oregano/tor/bin"
+cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../oregano/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
 $SHA256_PROG "$here/$pkgname/dist/bin/$binary"
-info "$binary has been placed in the 'electroncash' folder."
+info "$binary has been placed in the 'oregano' folder."
 popd
